# ====================================================================
# 1. FRONTEND
# ====================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: 019874521665.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
 
---
# ====================================================================
# 2. BACKEND VENTAS
# ====================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ventas
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ventas-backend
  template:
    metadata:
      labels:
        app: ventas-backend
    spec:
      containers:
      - name: ventas-container
        image: 019874521665.dkr.ecr.us-east-1.amazonaws.com/innovatech-ventas-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/$(DATABASE)
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretos
                  key: ROOT_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
 
---
# ====================================================================
# 3. BACKEND DESPACHOS
# ====================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-despacho
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: despacho-backend
  template:
    metadata:
      labels:
        app: despacho-backend
    spec:
      containers:
      - name: despacho-container
        image: 019874521665.dkr.ecr.us-east-1.amazonaws.com/innovatech-despacho-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"