apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-base-datos-proyecto # Este es el nombre que buscará tu Deployment de MySQL
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3 # Debe coincidir EXACTAMENTE con el metadata.name de tu StorageClass en Terraform
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password_secreto_del_proyecto"
        - name: MYSQL_DATABASE
          value: "bd_sistema"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-base-datos-proyecto # Llama al PVC declarado arriba
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  ports:
  - port: 3306
  selector:
    app: mysql